version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
          - 8081:8080
          - 50000:50000
        container_name: jenkins
        volumes:
          - ~/jenkins:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/local/bin/docker:/usr/local/bin/docker
    tomcat:    
        image: tomcat
        volumes:
          - ./target/LoginWebApp-1.war:/usr/local/tomcat/webapps/LoginWebApp.war
        ports:
          - '8082:8080'